spring:
  application:
    name: client-readerv2
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

server:
  port: 8082

replica:
  read:
    queue: read_queue_1