server:
  port: 8080
spring:
  application:
    name: replicasV2
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
replica:
  id: ${REPLICA_ID}
  file:
    path: ./data/replica${REPLICA_ID}/data.txt
  read:
    queue: read_queue_${REPLICA_ID}
  write:
    queue: write_queue_${REPLICA_ID}